# Generated by Django 4.2.14 on 2024-07-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0002_agent_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agency',
            field=models.CharField(default='Unspecified Agency', max_length=100),
        ),
    ]
