# Generated by Django 4.2.14 on 2024-07-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0004_buyer_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='homerating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
