# Generated by Django 4.2.14 on 2024-07-15 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0005_alter_buyer_homerating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='homerating',
            new_name='homeRating',
        ),
    ]
